//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int ID { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string SubArea { get; set; }
        public string CompleteAddress { get; set; }
    }
}
