//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserInterestedID { get; set; }
        public Nullable<int> ShowroomInterestedID { get; set; }
        public Nullable<int> UserCarID { get; set; }
        public Nullable<int> ShowroomCarID { get; set; }
        public string Number { get; set; }
        public string Purpose { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public bool Isactive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tblCar tblCar { get; set; }
        public virtual tblShowroom tblShowroom { get; set; }
        public virtual tblUserAdd tblUserAdd { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
