//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public int ID { get; set; }
        public string BlogText { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Image { get; set; }
        public int ShowroomId { get; set; }
        public Nullable<int> Showrooms_ID { get; set; }
        public string Title { get; set; }
        public bool Isactive { get; set; }
        public bool Isarchive { get; set; }
        public string Path { get; set; }
        public string BlogsURL { get; set; }
    
        public virtual tblShowroom tblShowroom { get; set; }
    }
}
