//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFavAdd
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isarchived { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblCar tblCar { get; set; }
    }
}
