//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AdURL { get; set; }
        public Nullable<int> FromUserID { get; set; }
        public Nullable<int> FromShowroomID { get; set; }
        public Nullable<bool> IsShowroomInterested { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblShowroom tblShowroom { get; set; }
    }
}
