//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int ID { get; set; }
        public Nullable<int> ShowroomID { get; set; }
        public Nullable<decimal> Recievable { get; set; }
        public System.DateTime RecievableFromDate { get; set; }
        public System.DateTime RecievableToDate { get; set; }
        public Nullable<decimal> Recieved { get; set; }
        public System.DateTime RecievedFromDate { get; set; }
        public System.DateTime RecievedToDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isarchive { get; set; }
    
        public virtual tblShowroom tblShowroom { get; set; }
    }
}
