//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQueryDetail
    {
        public int ID { get; set; }
        public Nullable<int> QueryID { get; set; }
        public Nullable<int> FromUser { get; set; }
        public Nullable<int> ToUser { get; set; }
        public string Message { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isarchive { get; set; }
    
        public virtual tblQuery tblQuery { get; set; }
    }
}
