//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermission
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> MakeAnnoucment { get; set; }
        public Nullable<bool> ShowAnnoucment { get; set; }
        public Nullable<bool> AddUser { get; set; }
        public Nullable<bool> EditUser { get; set; }
        public Nullable<bool> DeleteUser { get; set; }
        public Nullable<bool> ShowUsers { get; set; }
        public Nullable<bool> AddShowroom { get; set; }
        public Nullable<bool> EditShowroom { get; set; }
        public Nullable<bool> DeleteShowroom { get; set; }
        public Nullable<bool> ShowShowroom { get; set; }
        public Nullable<bool> AddUnionMember { get; set; }
        public Nullable<bool> EditUnionMember { get; set; }
        public Nullable<bool> DeleteUnionMember { get; set; }
        public Nullable<bool> ShowUnionMember { get; set; }
        public Nullable<bool> ManagUserAds { get; set; }
        public Nullable<bool> ManagShowroomAds { get; set; }
        public Nullable<bool> MakePayments { get; set; }
        public Nullable<bool> ShowPayments { get; set; }
        public Nullable<bool> EditProfile { get; set; }
        public Nullable<bool> AddUnionRole { get; set; }
        public Nullable<bool> EditUnionRole { get; set; }
        public Nullable<bool> DeleteUnionRole { get; set; }
        public Nullable<bool> ShowUnionRole { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
