//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRCar.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZone
    {
        public int ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual tblCity tblCity { get; set; }
    }
}
